image: golang

stages:
  - build-lib
  - build

build-mix:
  stage: build-lib
  script:
   - go build ./mix

build-shake:
  stage: build
  script:
   - go build ./shake

build-stir:
  stage: build
  script:
   - go build ./stir
